### ISSUE TITLE
Unable to create ("set") DOCUMENT variables

### ISSUE THREAD

**Issue by calebbergman** [mdObject/GECentricity#1]
`$mdObject.clinicalDocument.val("MyVariable", "High");` results in the following MEL trace error:

ML Thread [MelTrace] >{DOCUMENT.MyVariable="High"}
ML Thread [MelTrace] execute>Document.MyVariable = "High"
ML Thread [MelTrace] results>ERROR: 32786 COULDN'T FIND THE SYMBOL
ML Thread [MelTrace] ERROR: 32786 COULDN'T FIND THE SYMBOL

I've ran into this same issue in the past myself trying to perform a `Mel.eval("{DOCUMENT.MyVariable = MyValue}")` directly. Apparently it doesn't like attempting to instantiate a brand new DOCUMENT variable on-the-fly. I presume it has something to do with the fact that upon form compilation (or instantiation) development-time variables get assigned new, unique names, like `DOCUMENT.H_6165_1438792667_768`.

**Comment by hwinston** [comment]
This is a limitation of the Centricity EMR / CPS. It isn’t a matter of the naming conventions, but it can be a factor if you aren’t tracking them. At the moment, only the process of initializing an encounter form in an update allows for the creation of new DOCUMENT.TEMP variables. They may be read and written to, but not instantiated in this way.

_Tygh

**Comment by calebbergman** [comment]
I was afraid that was the case. Having to maintain a separate set of variables and re-importing the .ckt every time something changes...leaves a sour taste in my mouth. I suppose you could utilize a text component instead. Still not ideal, but better.

**Comment by aaltotsky** [comment]
In order to use dynamic variables, you have to declare them in the .xlw file. For example:
{ /****WATCHER EXPRESSIONS****/ }
{!// Declare the document variables
	DOCUMENT.Height
}
Now you can use them in your form like:
1. To assign the existing value to HTML variable (I use jQuery here): 
$("#Height").val($mdObject.clinicalDocument.val("Height"));
2. To save data from form:
var height = $("#Height").val();
$mdObject.clinicalDocument.val("Height", height);
3. And finally to display in the document using  .xlt file:
{/****START OF FORM TRANSLATION BODY****/
}{cfmt(Document.Title, "B,2", "", "","\r\n")
+cfmt(Document.Height, "B,1", " Height:", "","in.")
}

If you add new variable, just add it to .xlw file. 

For "object" storage (temp variable ) you can use the "variables" to store JSON. Only one mdObject_variables need to be declared in .xlw file. 


PS. The above is partial example from the Lab training of the "Introduction to HTML Encounter Form Development" class provided by mdObject, Inc.
