### ISSUE TITLE
Angular.js script Error

### ISSUE THREAD

**Issue by cycle4passion** [mdObject/GECentricity#2]
Demo fails to load, Centricity Data absent. Any help is appreciated.

![image](https://user-images.githubusercontent.com/6192217/32139995-128a78ae-bc28-11e7-9118-2fab6a5d5e18.png)

Environment:
Windows 8.1 Pro
IE 11, localhost added for compatibility mode.
CentricityEMR9.8
Regsvr32 "C:\Program Files (x86)\Centricity EMR 9.8 Evaluation\GE.EMR.Msg.IF.dll" was successful
Unmodified mdObject Directory placed at: 
C:\Program Files (x86)\Centricity EMR 9.8 Evaluation\jboss\server\default\deploy\Default.ear\CentricityPracticeWS.war\EncounterForms\mdObject
link in Demo.html to angular.js is still valid: https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js

**Comment by aaltotsky** [comment]
Hello @cycle4passion,
How did you call the demo page? Have you tried to "open this page in Internet Explorer (IE)" link?
The IE has the F12 (Development tools) that may give you more info.

**Comment by cycle4passion** [comment]
Hopefully I have the correct directory structure:

`C:\Program Files (x86)\Centricity EMR 9.8 Evaluation\jboss\server\default\deploy\Default.ear\CentricityPracticeWS.war\EncounterForms\mdObject\Demo.html`

I call via .md quicktext : `{show_html_form("//localserver/EncounterForms/mdObject/Demo.html","mdObject")}`

no errors under IE 11 Dev Tools
[https://www.dropbox.com/s/xsewcul3fu3topq/mdo.mp4?dl=0](Video)

**Comment by aaltotsky** [comment]
I recommend not to use the EncounterForms folder.
Default location for your own HTML Encounter forms in CPS12+: 
> %JBOSS.SERVER.HOME.DIR%\server\default\deploy\demo.ear\CentricityPracticeWS.war\
EMR9.8 Evaluation: 
> 	C:\Program Files (x86)\Centricity EMR 9.8 Evaluation\jboss\server\default\deploy\Default.ear\CentricityPracticeWS.war\

But I see the issue. I was able to replicate it.

The issue is in module initializer:

[AngularJs Error](https://docs.angularjs.org/error/$injector/modulerr?p0=mdObjectDemo&p1=Error:%20%5B$injector:nomod%5D%20http:%2F%2Ferrors.angularjs.org%2Fundefined%2F$injector%2Fnomod%3Fp0%3DmdObjectDemo%0A%20%20%20at%20Anonymous%20function%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:20:113)%0A%20%20%20at%20a%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:19:334)%0A%20%20%20at%20Anonymous%20function%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:20:7)%0A%20%20%20at%20Anonymous%20function%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:28:432)%0A%20%20%20at%20q%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:7:259)%0A%20%20%20at%20e%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:28:374)%0A%20%20%20at%20Xb%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:32:425)%0A%20%20%20at%20c%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:17:313)%0A%20%20%20at%20Wb%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:18:23)%0A%20%20%20at%20Oc%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.0%2Fangular.min.js:17:99)

We will try to fix it tonight or tomorrow.

In the main time, you could get the old version from the NuGet:
https://www.nuget.org/packages/mdObject.Centricity/

**Comment by aaltotsky** [comment]
Hello @cycle4passion,

Thank you for point to the issue with the code. This issue fixed. 

Get the latest from the master branch and be sure that you are using the correct file:
`{show_html_form("//localserver/EncounterForms/mdObject/examples/angular.js/index.html","mdObject")}`

We switched the project to Typescript and WebPack.  

The "old" javascript component exist in the:
`{show_html_form("//localserver/EncounterForms/mdObject/old-data/Demo.html","mdObject")}`

**Comment by cycle4passion** [comment]
I can confirm the fix is working for me. Thank you.
